version: '3.8'
services:
  app:
    build: .
    image: go_mysql
    container_name: go_mysql
    ports:
      - "80:80"
    depends_on:
      - database
  
  database:
    image: mysql:latest
    container_name: mysql
